name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

env:
  JABBA_INDEX: "https://github.com/typelevel/jdk-index/raw/main/index.json"

jobs:
  build:
    name: Tests

    steps:
      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v13
        with:
          java-version: graalvm@11

      - name: Tests
        run: sbt test
